#cloud-config
package_update: true
packages:
  - qemu-guest-agent
runcmd:
  - - systemctl
    - enable
    - '--now'
    - qemu-guest-agent.service
ssh_authorized_keys:
  - >-
    ssh-rsa AAAAB3NzaC1yc2EAAAADaAasdfasdfasdfasdfasdfasdfasdfasdflQl13LkJ4tPQL+ew1Em9VyD7hY25QtAbs26EEmc= user@host
ca_certs:
  trusted:
  - |
   -----BEGIN CERTIFICATE-----
   MIIBvjCCAWOgAwIBAgIBADAKBggqhkjOPQQDAjBGMRwwGgYDVQQKExNkeW5hbWlj
   bGlzdGVuZXItb3JnMSYwJAYDVQQDDB1keW5hbWljbGlzdGVuZXItY2FAMTY5MzU4
   MDk2MjAeFw0yMzA5MDExNTA5MjJaFw0zMzA4MjkxNTA5MjJaMEYxHDAaBgNVBAoT
   E2R5bmFtaWNsaXN0ZW5lci1vcmcxJjAkBgNVBAMMHWR5bmFtaWNsaXN0ZW5lci1j
   asdfasdfasdfasdfMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEvRmFtPsSqxW+
   asdfasdfasdfasdfPAKD2WKeph/b+5o1XeTi6nR0IIC4Szu7ZoquzNCWsXBdoBfs
   asdfasdfasdfasdfDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYD
   asdfasdfasddasdfbIYsJ7MmGNMUshdGn2dyMAoGCCqGSM49BAMCA0kAMEYCIQCO
   asdfasdfasdfasdf6vmqL4P6CQhT9Jm98F/ZN0RKpgIhANOCEZxYY/+4IJOHDeZB
   asdfasdfasdfasdf
   -----END CERTIFICATE-----
write_files:
- content: |

    # My new file created wirh cloudinit with terraform
    Example from terraform

  path: /root/foo

